# Generated by Django 5.2.3 on 2026-01-22 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stavka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=100)),
                ('opis', models.TextField(blank=True, null=True)),
                ('cijena', models.DecimalField(decimal_places=2, max_digits=8)),
                ('kategorija', models.CharField(choices=[('toplo', 'Topli napici'), ('sokovi', 'Sokovi'), ('pivo', 'Pivo'), ('zestoka', 'Zestoka pica'), ('vino', 'Vino'), ('kokteli', 'Kokteli')], default='ostalo', max_length=20)),
            ],
        ),
    ]
