# Generated by Django 5.2.3 on 2025-06-28 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meni', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stavka',
            old_name='cena',
            new_name='cijena',
        ),
    ]
