# Generated by Django 5.2.3 on 2025-07-11 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meni', '0002_rename_cena_stavka_cijena'),
    ]

    operations = [
        migrations.AddField(
            model_name='stavka',
            name='kategorija',
            field=models.CharField(choices=[('pice', 'Piće'), ('hrana', 'Hrana'), ('toplo', 'Topli napici'), ('alkohol', 'Alkohol'), ('ostalo', 'Ostalo')], default='ostalo', max_length=20),
        ),
    ]
