# Generated by Django 5.2.3 on 2025-07-12 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meni', '0003_stavka_kategorija'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stavka',
            name='kategorija',
            field=models.CharField(choices=[('toplo', 'Topli napici'), ('sokovi', 'Sokovi'), ('pivo', 'Pivo'), ('zestoka', 'Zestoka pica'), ('vino', 'Vino'), ('kokteli', 'Kokteli')], default='ostalo', max_length=20),
        ),
    ]
