# Generated by Django 5.2.3 on 2026-01-22 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meni', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sirovina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=100)),
                ('jedinica_mjere', models.CharField(max_length=20)),
                ('kolicina', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Recept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kolicina', models.FloatField(help_text='Količina sirovine po jednoj jedinici stavke')),
                ('stavka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meni.stavka')),
                ('sirovina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lager.sirovina')),
            ],
        ),
    ]
