# Generated by Django 5.2.3 on 2026-02-05 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sirovina',
            name='min_kolicina',
            field=models.FloatField(default=0),
        ),
    ]
