# Generated by Django 5.2.3 on 2026-01-22 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Narudzba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sto_broj', models.PositiveIntegerField()),
                ('napomena', models.TextField(blank=True)),
                ('datum', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('kreirana', 'Kreirana'), ('na_sanku', 'Na šanku'), ('zavrsena', 'Završena')], default='kreirana', max_length=20)),
                ('konobar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='narudzbe_konobar', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefon', models.CharField(blank=True, max_length=20)),
                ('adresa', models.TextField(blank=True)),
                ('uloga', models.CharField(choices=[('sef', 'Šef'), ('konobar', 'Konobar'), ('sank', 'Šank')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
