# Generated by Django 5.2.3 on 2025-07-05 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('korisnici', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='uloga',
            field=models.CharField(choices=[('sef', 'Šef'), ('konobar', 'Konobar')], max_length=20),
        ),
    ]
