# Generated by Django 5.2.3 on 2025-07-05 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('korisnici', '0002_alter_profil_uloga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='uloga',
            field=models.CharField(choices=[('sef', 'Šef'), ('konobar', 'Konobar'), ('sank', 'Šank')], max_length=20),
        ),
    ]
