# Generated by Django 5.2.3 on 2025-07-06 19:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('korisnici', '0003_alter_profil_uloga'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Narudzba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sto_broj', models.PositiveIntegerField()),
                ('napomena', models.TextField(blank=True)),
                ('datum', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('kreirana', 'Kreirana'), ('na_sanku', 'Na šanku'), ('zavrsena', 'Završena')], default='kreirana', max_length=20)),
                ('konobar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='narudzbe_konobar', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
