# Generated by Django 5.2.3 on 2025-12-27 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stolovi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sto',
            name='status',
            field=models.CharField(choices=[('slobodan', 'Slobodan'), ('zauzet', 'Zauzet'), ('rezervisan', 'Rezervisan')], default='slobodan', max_length=20),
        ),
    ]
