# Generated by Django 5.2.3 on 2025-06-28 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meni', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Narudzba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateTimeField(auto_now_add=True)),
                ('stavke', models.ManyToManyField(related_name='narudzbe', to='meni.stavka')),
            ],
        ),
    ]
