# Generated by Django 5.2.3 on 2026-01-22 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meni', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Narudzba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sto_broj', models.PositiveIntegerField()),
                ('datum', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('u_pripremi', 'U pripremi'), ('spremna', 'Spremna za posluženje'), ('zavrsena', 'Završena'), ('placena', 'Plaćena'), ('ZATVORENA', 'Zatvorena')], default='u_pripremi', max_length=20)),
                ('konobar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-datum'],
            },
        ),
        migrations.CreateModel(
            name='StavkaNarudzbe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kolicina', models.PositiveIntegerField(default=1)),
                ('narudzba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stavke', to='narudzba.narudzba')),
                ('stavka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meni.stavka')),
            ],
        ),
    ]
