# Generated by Django 5.2.3 on 2025-07-05 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meni', '0002_rename_cena_stavka_cijena'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Narudzba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sto_broj', models.PositiveIntegerField()),
                ('napomena', models.TextField(blank=True)),
                ('datum', models.DateTimeField(auto_now_add=True)),
                ('konobar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StavkaNarudzbe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kolicina', models.PositiveIntegerField(default=1)),
                ('narudzba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stavke', to='narudzba.narudzba')),
                ('stavka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meni.stavka')),
            ],
        ),
    ]
