# Generated by Django 5.2.3 on 2025-07-05 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narudzba', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='narudzba',
            name='status',
            field=models.CharField(choices=[('u_pripremi', 'U pripremi'), ('spremna', 'Spremna za posluženje'), ('zavrsena', 'Završena')], default='u_pripremi', max_length=20),
        ),
    ]
