# Generated by Django 5.2.3 on 2025-07-11 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narudzba', '0002_narudzba_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='narudzba',
            name='status',
            field=models.CharField(choices=[('u_pripremi', 'U pripremi'), ('spremna', 'Spremna za posluženje'), ('zavrsena', 'Završena'), ('placena', 'Plaćena')], default='u_pripremi', max_length=20),
        ),
    ]
