# Generated by Django 5.2.3 on 2025-07-12 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('narudzba', '0003_alter_narudzba_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='narudzba',
            name='napomena',
        ),
    ]
