# Generated by Django 5.2.3 on 2025-12-07 20:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narudzba', '0004_remove_narudzba_napomena'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='narudzba',
            options={'ordering': ['-datum']},
        ),
        migrations.AlterField(
            model_name='narudzba',
            name='konobar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
