# Generated by Django 5.2.3 on 2025-12-07 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narudzba', '0005_alter_narudzba_options_alter_narudzba_konobar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='narudzba',
            name='status',
            field=models.CharField(choices=[('u_pripremi', 'U pripremi'), ('spremna', 'Spremna za posluženje'), ('zavrsena', 'Završena'), ('placena', 'Plaćena'), ('ZATVORENA', 'Zatvorena')], default='u_pripremi', max_length=20),
        ),
    ]
